### ISSUE TITLE
Client crashes

### ISSUE THREAD

**Issue by 79ak47** [OrtusMC/OrtusLib#56]
[crash-2024-10-27_03.53.42-client.txt](https://github.com/user-attachments/files/17531827/crash-2024-10-27_03.53.42-client.txt)

**Comment by MaxBogomol** [comment]
update oculus

**Comment by 79ak47** [comment]
> 更新 Oculus

可是Oculus已经停更了

**Comment by MaxBogomol** [comment]
You don't have the latest version of Oculus.

**Comment by 79ak47** [comment]
> You don't have the latest version of Oculus.

Sorry, I just found out that my oculus is not the latest version (the beta version downloaded a few days before the latest version came out). I'll try it again in the morning. Thank you very much!
